name: Update Latest Projects

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README with latest repos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: repos
          feed_list: "https://github.com/somansinghal.atom"
