name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate pacman animation
        uses: Platane/snk@v3
        with:
          github_user_name: somansinghal
          outputs: |
            dist/pacman-contribution-graph.svg

      - name: Push pacman animation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
