name: Update Latest Repositories

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with latest repos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: repos
          feed_list: "https://github.com/somansinghal.atom"
